server:  port: 8081

#POSTGRESQL
spring:  datasource:     url: jdbc:postgresql://localhost:5432/demo_mvc?user=postgres&password=root
    username: root
    password: root   #THYMELEAF      thymeleaf:    cache: false


#JPA  jpa:    hibernate:      ddl-auto: update
    show-sql: true
    open-in-view: true